
#Clear database before re-seeding
Observation.destroy_all
Mushroom.destroy_all
#Phylum: Basidiomycota
Mushroom.create(phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

#Class: Agaricomycetes
Mushroom.create(classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

#Order: Agaricales
Mushroom.create(order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

Mushroom.create(family: 'Fistulinaceae', order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Fistulina', family: 'Fistulinaceae', order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'hepatica', genus: 'Fistulina', family: 'Fistulinaceae', order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Beefsteak Polypore', description: 'The flesh of this polypore is off-white to pinkish, with streaks of red. It exudes a red juice. It looks like a piece of raw meat! Uniquely, the tubes of this polypore fungus, while closely packed, are free from each other.', keywords: 'polypores solitary clustered medium tree-hardwood tree-trunk red pore-surface-pink pore-texture-smooth')
Mushroom.create(genus: 'Porodisculus', family: 'Fistulinaceae', order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'pendulus', genus: 'Porodisculus', family: 'Fistulinaceae', order: 'Agaricales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: 'This is the smallest polypore species.', keywords: 'polypores solitary grouped small tree-hardwood tree-branch cream brown white pore-surface-cream pore-texture-smooth')

#Order: Hymenochaetales
Mushroom.create(order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

Mushroom.create(family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Inonotus', family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'dryadeus', genus: 'Inonotus', family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Oak Bracket, Weeping Polypore, Weeping Conk', description: 'Exudes amber-colored droplets when young. Inonotus dryadeus causes a white rot of the butt and roots of living oaks.', keywords: 'polypores solitary large tree-hardwood tree-base gray brown white pore-surface-cream pore-texture-smooth')
Mushroom.create(genus: 'Phellinus', family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'gilvus', genus: 'Phellinus', family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Mustard Yellow Polypore', description: 'These often have brownish cap and yellow margin.', keywords: 'polypores solitary grouped medium tree-hardwood tree-softwood tree-trunk tree-branch brown orange red yellow pore-surface-brown pore-texture-smooth')
Mushroom.create(species: 'robiniae', genus: 'Phellinus', family: 'Hymenochaetaceae', order: 'Hymenochaetales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Cracked-Cap Polypore', description: 'Primarily found on living or dead black locust trees year-round. Several other polypores develop cracks in age but few occur on black locust.', keywords: 'polypores solitary large tree-hardwood tree-trunk black brown pore-surface-brown pore-texture-smooth')

#Order: Polyporales
Mushroom.create(order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

Mushroom.create(family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Daedalea', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'quercina', genus: 'Daedalea', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Oak Mazegill', description: 'Compare to Daedaleopsis confragosa which superficially resembles it.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch gray brown white pore-surface-white pore-texture-other')
Mushroom.create(genus: 'Fomitopsis', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'betulinus', genus: 'Fomitopsis', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Birch Polypore', description: 'Oetzi, the 5000 year old "Ice man" had among his possessions pieces of this fungus which might have been used for medicinal purposes.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch brown white pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Ischnoderma', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', description: '', keywords: '')
Mushroom.create(species: 'resinosum', genus: 'Ischnoderma', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Resinous Polypore', description: 'The flesh of young specimens is soft and sappy (juicy) at first. May be mistaken for Ganoderma lobatum at a glance, but it is much softer.', keywords: 'polypores solitary grouped clustered medium large tree-hardwood tree-trunk tree-branch brown white pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Laetiporus', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Chicken of the woods, Sulphur Shelf', description: '', keywords: '')
Mushroom.create(species: 'cincinnatus', genus: 'Laetiporus', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Chicken of the woods', description: 'Unlike Laetiporus sulphureus, this species grows on the ground in rosette-like clusters and has white pores.', keywords: 'polypores clustered rosette large tree-hardwood tree-base orange white pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'sulphureus', genus: 'Laetiporus', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Chicken of the woods, Sulphur Shelf', description: 'One of the largest and most colorful fungi, it is also considered a choice edible with tender portions tasting like white chicken meat. Individual allergies can occur and specimens growing on certain substrates or consumed with alcohol are reported to cause digestive system upset.', keywords: 'polypores clustered large tree-hardwood tree-trunk orange yellow pore-surface-yellow pore-texture-smooth')
Mushroom.create(genus: 'Postia', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Blue Cheese Polypore, Conifer Blueing Bracket', description: '', keywords: '')
Mushroom.create(species: 'livens', genus: 'Postia', family: 'Fomitopsidaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Blue Cheese Polypore, Conifer Blueing Bracket', description: 'Odor fragrant. This polypore is soft, watery and spongy when fresh.', keywords: 'tyromyces oligoporus polypores solitary grouped medium tree-hardwood tree-softwood tree-trunk tree-branch white blue pore-surface-white pore-texture-smooth')

Mushroom.create(family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Ganoderma', family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'applanatum', genus: 'Ganoderma', family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: "Artist's Conk", description: "This is the well-known Artist's conk used by artists to etch drawings. Ganoderma lobatum resembles this species. A field test to help distinguish between the two species involves pressing into the cap surface with a thumb. If the surface cracks and fractures, the specimen is likely G. lobatum. The cap surface of G. applanatum is too hard to break in this manner by pressing in with a thumb.", keywords: 'polypores solitary grouped large tree-hardwood tree-trunk gray brown white pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'curtisii', genus: 'Ganoderma', family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: 'polypores solitary clustered medium tree-hardwood tree-base tree-trunk red orange yellow purple multicolor cream pore-surface-brown pore-texture-smooth')
Mushroom.create(species: 'lobatum', genus: 'Ganoderma', family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: 'Somewhat soft Ganoderma species that stains black on the white pore surface.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch red brown white pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'sessile', genus: 'Ganoderma', family: 'Ganodermataceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'American Reishi, American Lingzhi', description: "American reishi mushroom that's sought after for it's medicinal properties, though they are not as potent as it's Asian cousin, Ganoderma lingzhi. It's recognizable by it's shiny smooth reddish upper surface.", keywords: 'lucidum lingzhi polypores solitary clustered medium tree-hardwood tree-base tree-trunk red cream brown pore-surface-cream pore-texture-smooth')

Mushroom.create(family: 'Meripilaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Grifola', family: 'Meripilaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'frondosa', genus: 'Grifola', family: 'Meripilaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Hen of the Woods, Maitake', description: 'This weak parasite of tree roots can be found at the same site year after year. It is a highly sought after edible species.', keywords: 'polypores clustered rosette large tree-hardwood tree-base gray brown pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Meripilus', family: 'Meripilaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'sumstinei', genus: 'Meripilus', family: 'Meripilaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Black-staining Polypore', description: 'Clusters of Meripilus sumstinei may attain diameters of 40 cm or more. Pore surface bruises black.', keywords: 'polypores clustered rosette large tree-hardwood tree-base gray brown yellow pore-surface-white pore-texture-smooth')

Mushroom.create(family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Cerioporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'squamosus', genus: 'Cerioporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: "Dryad's Saddle", description: 'The flesh of this fungus smells like watermelon rind.', keywords: 'polyporus polypores solitary grouped large tree-hardwood tree-trunk brown yellow pore-surface-white pore-texture-other')
Mushroom.create(genus: 'Daedaleopsis', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'confragosa', genus: 'Daedaleopsis', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Thin Walled Maze Polypore', description: 'Compare to Daedalea quercina which superficially resembles it.', keywords: 'polypores solitary grouped medium tree-hardwood tree-branch gray brown pore-surface-white pore-texture-other')
Mushroom.create(genus: 'Fomes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'fomentarius', genus: 'Fomes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Hoof Fungus, Tinder Polypore', description: 'This hoof-shaped conk has a long traditional use as a tinder for starting fires. At the following website read about Oetzi, the 5000 year old "Ice man" who was found in possession of this fungus and perhaps used it to start fires.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk gray brown green pore-surface-brown pore-texture-smooth')
Mushroom.create(genus: 'Fuscopostia', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'fragilis', genus: 'Fuscopostia', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Brown-staining Cheese Polypore', description: 'Specimens are soft when fresh and much harder in age. The reddish-brown staining reaction is very quick.', keywords: 'polypores solitary grouped medium tree-softwood tree-trunk tree-branch white yellow brown pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Hapalopilus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'nidulans', genus: 'Hapalopilus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Tender Nesting Polypore, Purple Dye Polypore, Cinnamon Bracket', description: 'There are reports of serious toxicity associated with eating this polypore. All parts turn purple with KOH or ammonia.', keywords: 'rutilans polypores solitary grouped medium tree-hardwood tree-trunk tree-branch brown orange pore-surface-orange pore-texture-other')
Mushroom.create(genus: 'Neofavolus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'alveolaris', genus: 'Neofavolus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Hexagonal-pored Polypore', description: 'Compare to Polyporus arcularius which has a circular cap and a central stalk.', keywords: 'polyporus polypores solitary grouped small tree-hardwood tree-branch orange pore-surface-white pore-texture-other')
Mushroom.create(genus: 'Perenniporia', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'medulla-panis', genus: 'Perenniporia', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Pancake Crust', description: 'It is a plant pathogen that infects stone fruit trees.', keywords: 'polypores crust small tree-hardwood tree-trunk tree-branch white beige pore-surface-white pore-texture-toothed')
Mushroom.create(genus: 'Polyporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'arcularius', genus: 'Polyporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Spring Polypore', description: 'One of the first mushrooms to appear in the spring. Compare to P. brumalis which has a darker cap without a fringed margin and smaller pores.', keywords: 'polypores solitary grouped small tree-hardwood tree-trunk tree-branch brown pore-surface-white pore-texture-other')
Mushroom.create(species: 'brumalis', genus: 'Polyporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Winter Polypore', description: 'Compare to P. arcularius which has a paler, scaly cap with a fringed margin and larger pores.', keywords: 'polypores solitary grouped small tree-hardwood tree-trunk tree-branch brown pore-surface-white pore-texture-other')
Mushroom.create(genus: 'Pycnoporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'cinnabarinus', genus: 'Pycnoporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Cinnabar Polypore', description: 'cinnabarinus means "bright red" or "vermillion" in reference to the coloration of this fungus.', keywords: 'polypores solitary grouped medium tree-hardwood tree-branch orange pore-surface-orange pore-texture-smooth')
Mushroom.create(genus: 'Royoporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'badius', genus: 'Royoporus', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Black-footed Polypore', description: 'Dark reddish-brown upper surface with a thin, wavy or lobed margin. The base of the stipe is black, hence the common name.', keywords: 'polyporus polypores solitary grouped medium tree-hardwood tree-trunk tree-branch red brown black pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Spongipellis', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'pachyodon', genus: 'Spongipellis', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Marshmallow Polypore', description: 'This parasite causes a white heart-rot of living broadleafed trees, particularly oak.', keywords: 'sarcodontia polypores solitary clustered small tree-hardwood tree-trunk tree-branch white cream pore-surface-white pore-texture-toothed')
Mushroom.create(genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'betulina', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Gilled Polypore', description: 'The gills are tough and leathery, unlike the gills of the true gilled mushrooms. The pores of this poroid fungus develop into gill-like structures.', keywords: 'polypores solitary grouped medium tree-hardwood tree-branch multicolor brown green pore-surface-white pore-texture-other')
Mushroom.create(species: 'conchifer', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Little Nest Polypore', description: "The cups may be found by themselves. They are sterile and may be mistaken for a cup fungus or a bird's nest fungus. If just the shelves are present, this fungus is difficult to identify. The combination is distinctive.", keywords: 'polypores grouped small tree-hardwood tree-branch white brown pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'elegans', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'White Maze Polypore', description: 'Unlike Daedaleopsis confragosa which also has a maze-like pore surface, the pore surface of Trametes elegans does not bruise pinkish-brown.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch white gray green pore-surface-white pore-texture-other')
Mushroom.create(species: 'gibbosa', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Lumpy Bracket', description: 'Often the pale upper surface is discoloured by green algae, the more so in the zones further from the margin. That and the slot-like pores (other whitish Trametes species have round or oval pores) makes this a very easy polypore to identify.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch white green pore-surface-white pore-texture-other')
Mushroom.create(species: 'hirsuta', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Hairy Bracket', description: 'Trametes hirsuta exhibits a good amount of variation in the appearance of the cap and pore surfaces, making identification sometimes uncertain.', keywords: 'polypores solitary clustered medium tree-hardwood tree-trunk tree-branch gray yellow brown pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'pubescens', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: 'The azonate, finely hairy, uniformly creamy or yellowish caps are a good combination of field identification characters.', keywords: 'polypores solitary grouped small tree-hardwood tree-trunk tree-branch white cream beige yellow pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'suaveolens', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: 'The anise smell of young specimens is quite distinctive together with the brown bruising reaction and overall whistish color. Dyers are particularly interested in this species as it yields a much sought purple dye.', keywords: 'polypores solitary medium tree-hardwood tree-trunk tree-branch white beige brown pore-surface-white pore-texture-smooth')
Mushroom.create(species: 'versicolor', genus: 'Trametes', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Turkey Tail', description: 'This very colorful polypore may be the most common decomposer of hardwoods in North America.', keywords: 'polypores clustered small tree-hardwood tree-trunk tree-branch multicolor white brown pore-surface-white pore-texture-smooth')
Mushroom.create(genus: 'Tyromyces', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'chioneus', genus: 'Tyromyces', family: 'Polyporaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'White Cheese Polypore', description: 'When fresh, this polypore feels soft and watery. In fact, droplets of water are easily squeezed out of it. The polypore has a fragrant odor when fresh.', keywords: 'polypores solitary grouped medium tree-hardwood tree-trunk tree-branch white pore-surface-white pore-texture-smooth')

Mushroom.create(family: 'Steccherinaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Irpex', family: 'Steccherinaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'lacteus', genus: 'Irpex', family: 'Steccherinaceae', order: 'Polyporales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: 'Milk-white Toothed Polypore', description: 'Irpex lacteus is a white-rot fungus that inhabits mainly angiosperm branches and trunks.', keywords: 'polypores crust small tree-hardwood tree-softwood tree-trunk tree-branch white cream beige yellow pore-surface-white pore-texture-toothed')

#Order: Russulales
Mushroom.create(order: 'Russulales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')

Mushroom.create(family: 'Bondarzewiaceae', order: 'Russulales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(genus: 'Bondarzewia', family: 'Bondarzewiaceae', order: 'Russulales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: '', description: '', keywords: '')
Mushroom.create(species: 'berkeleyi', genus: 'Bondarzewia', family: 'Bondarzewiaceae', order: 'Russulales', classis: 'Agaricomycetes', phylum: 'Basidiomycota', common_name: "Berekeley's Polypore", description: "Berkeley's polypore causes a butt rot of living trees. When young, the flesh exudes a white latex. When it first emerges from the ground it looks like a collection of thick, irregular knobby fingers. The 'fingers' expand into overlapping shelves. The entire rosette of overlapping caps may be a meter or more across.", keywords: 'polypores rosette large tree-hardwood tree-base cream beige yellow pore-surface-white pore-texture-smooth' )